version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /backend/data/postgres
    volumes:
      - postgres-db:/backend/data/postgres
    ports:
      - "5432:5432"

volumes:
  postgres-db:
    driver: local